version: '3.3'
services:
  mongo:
    command: mongod
    image: mongo:3.6.3
    ports:
      - "27018:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    build:
      context: "./api"
      dockerfile: Dockerfile
    volumes:
      - "./api/src:/app/src"
    ports:
      - "3010:3000"
      - "9229:9229"
#  web:
#    build:
#      context: "./web"
#      dockerfile: Dockerfile
#    volumes:
#      - "./web/src:/app/src"
#    environment:
#      NODE_ENV: development
#      HRM_HOST: "0.0.0.0"
#    ports:
#      - "3011:3000"
