version: 2.1

# Define the jobs we want to run for this project
jobs:
  deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v DROPLET_USER@DROPLET_IP "./deploy_project.sh"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master