FROM node:15.11.0 as builder

WORKDIR /app

COPY ./package.json ./
RUN npm i
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD nginx -g 'daemon off;'
